on: [pull_request]

jobs:
  build_test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Check build (Strict)
        run: cargo build --verbose --release --features "strict"
      - name: Run tests
        run: cargo test --verbose